# Generated by Django 5.2.4 on 2025-07-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_mascota_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateTimeField()),
                ('tipo_servicio', models.CharField(choices=[('corte', 'Corte de pelo'), ('baño', 'Baño'), ('uñas', 'Corte de uñas'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_peluqueria', to='pacientes.mascota')),
            ],
        ),
    ]
